---
pool: 
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

trigger:
  - main
steps:
  - task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
  
  - script: sudo apt install npm
    displayName: 'npm install'
  - script: npm run build
    displayName: 'npm build'
  
    