---
- name: install wildfly
  hosts: all
  become: yes
  vars: 
    version: 11
  tasks:
   - name: install java
     package:
       name: "{{ java_pacakage_name }}"
       update_cache: yes
       state: present