---
- name: install wildfly
  hosts: all
  become: yes
  vars: 
    version: "11"
  tasks:
   - name: install default-jdk
     apt:
       name: "openjdk-{{ version }}-jdk"
       update_cache: yes
       state: present