---
pool: 
  name: "Azure Pipelines"
  vmImage: 'ubuntu-latest'

trigger:
  - main

jobs:
  - job: disk_utilization
    displayName: utilization
    steps:
      - script: df -H
        displayName: disk_utilization running 

  - job: Shell_script
    displayName: scripting task
    steps:
     - script: bash ansible/AZURE DEVOPS/diskpipeline/script.sh
  
  - job: update_package
    displayName: package update
    steps:
      - script: sudo apt update
        displayName: ubuntu package is updating


